name: build

on:
  push:
    branches:    
      - build
jobs:
  build:

    env:
      BUILD_TYPE: Release

    runs-on: ubuntu-latest

    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libpulse-dev libasound2-dev libjack-dev locate

    - name: Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

    - name: Configure
      run: |
        mkdir dependencies
        mkdir local
        cd dependencies

        git clone https://github.com/thestk/rtaudio.git -b 5.2.0
        cd rtaudio
        ./autogen.sh
        ./configure --prefix=$PWD/../../local
        make
        make check
        make install
        cd ..

        export LD_LIBRARY_PATH=$PWD/local/lib/:$LD_LIBRARY_PATH

        sudo ldconfig
        sudo updatedb
      
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make

    - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: binaries
        path: |
          build/chimes

